version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: rocket-mysql
    command: mysqld --user=root --verbose
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
    environment:
      MYSQL_USER: "di"
      MYSQL_PASSWORD: "di@2020!"
      MYSQL_ROOT_PASSWORD: "di@2020!"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  ssdb:
    image: wendal/ssdb:latest
    container_name: rocket-ssdb
    volumes:
      - ./ssdb/data:/var/lib/ssdb/data
      - ./ssdb/conf/ssdb.conf:/etc/ssdb.conf
    restart: always

  caas_service:
    image: datainsiderco/caas-service:dev
    container_name: rocket-caas-service
    restart: always
    environment:
      NAME: user-profile
      MODE: production
    depends_on:
      - mysql
      - ssdb

  schema_service:
    image: datainsiderco/schema-service:main
    container_name: rocket-schema-service
    restart: always
    env_file:
      - .clickhouse.env
    environment:
      NAME: schema-service
      MODE: production
      HTTP_PORT: 8489
      THRIFT_PORT: 8487
    depends_on:
      - mysql
      - ssdb
      - caas_service

  bi_service:
    image: datainsiderco/bi-service:dev
    container_name: rocket-bi-service
    restart: always
    env_file:
      - .clickhouse.env
    environment:
      NAME: bi-service
      MODE: production
      HTTP_PORT: 8080
    depends_on:
      - mysql
      - ssdb
      - caas_service

  web:
    image: datainsiderco/rocket-bi-web:dev
    container_name: rocket-web
    volumes:
     - ./web/config:/app/config
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 30s

  nginx:
    image: nginx:latest
    container_name: rocket-nginx
    ports:
      - 5050:80
    volumes:
      - ./nginx_home/conf.d/:/etc/nginx/conf.d/
      - ./nginx_home/nginx.conf/:/etc/nginx/nginx.conf
      - ./nginx_home/log/:/var/log/nginx/
      - ./nginx_home/html:/var/www/html/public
    depends_on:
      - bi_service
      - web

networks:
  rocket_network:
