version: "3"

services:
  mysql:
    image: datainsiderco/rocket-mysql
    container_name: rocket-mysql
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - 3306:3306

  ssdb:
    image: datainsiderco/rocket-ssdb
    container_name: rocket-ssdb
    ports:
      - 8888:8888
    volumes:
      - ./ssdb/data:/var/lib/ssdb/data
    restart: always

  caas_service:
    image: datainsiderco/caas-service:dev
    container_name: rocket-caas-service
    restart: always
    environment:
      NAME: user-profile
      MODE: production
    depends_on:
      - mysql
      - ssdb

  schema_service:
    image: datainsiderco/schema-service:dev
    container_name: rocket-schema-service
    restart: always
    env_file:
      - .clickhouse.env
    environment:
      NAME: schema-service
      MODE: production
      HTTP_PORT: 8489
      THRIFT_PORT: 8487
    volumes:
      - ./schema-service/logs:/app/logs
    depends_on:
      - mysql
      - ssdb
      - caas_service

  bi_service:
    image: datainsiderco/bi-service:dev
    container_name: rocket-bi-service
    restart: always
    env_file:
      - .clickhouse.env
    environment:
      NAME: bi-service
      MODE: production
      HTTP_PORT: 8080
    depends_on:
      - mysql
      - ssdb
      - caas_service

  job_scheduler:
    image: datainsiderco/job-scheduler:dev
    container_name: rocket-job-scheduler
    restart: always
    environment:
      NAME: job-scheduler
      MODE: production
      HTTP_PORT: 8080
      THRIFT_PORT: 8084
    volumes:
      - ./job-scheduler/logs:/app/logs
    depends_on:
      - mysql
      - ssdb
      - caas_service

  job_worker:
    image: datainsiderco/job-worker:dev
    container_name: rocket-job-worker
    restart: always
    env_file:
      - .clickhouse.env
    volumes:
      - ./job-worker/logs:/app/logs
    environment:
      NAME: job-worker
      MODE: production
      HTTP_PORT: 8080

  web:
    image: datainsiderco/rocket-bi-web:dev
    container_name: rocket-web
    volumes:
     - ./web/config:/app/config
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 30s

  nginx:
    image: datainsiderco/rocket-nginx
    container_name: rocket-nginx
    ports:
      - 5050:80
    volumes:
      - ./nginx/log/:/var/log/nginx/
    depends_on:
      - bi_service
      - web

networks:
  rocket_network:
