version: '3'
services:
  bi_service:
    image: datainsiderco/bi-service:main
    container_name: rocket-bi-service
    restart: always
    environment:
      NAME: bi-service
      MODE: production
      HTTP_PORT: 8080
      CLICKHOUSE_HOST: ""
      CLICKHOUSE_HTTP_PORT: 8123
      CLICKHOUSE_TCP_PORT: 9000
      CLICKHOUSE_USERNAME: default
      CLICKHOUSE_PASSWORD: ""
      CLICKHOUSE_CLUSTER_NAME: ""
    volumes:
      - ./conf:/app/conf
      - ./logs:/app/logs
      - biservice-csv-dir:/tmp/csv

volumes:
  biservice-csv-dir:
    external: true

networks:
  default:
    external:
      name: rocket_network
